/**
 * @file test_network.c
 * @brief Unit tests for chain-id ↔ network resolution in src/network.c.
 *
 * Every "Network: …" line shown to the user is generated by this module:
 *   - get_network_name_from_chain_id() looks up the chain in the dynamic
 *     list first then the hardcoded NETWORK_MAPPING table,
 *   - get_network_as_string_from_chain_id() falls back to the decimal
 *     chain_id when no name is known,
 *   - get_displayable_ticker() picks between the dynamic / hardcoded /
 *     chain_config / "???" sources for the ticker badge,
 *   - app_compatible_with_chain_id() decides whether the running app may
 *     sign for a given chain at all.
 *
 * The tests stub the few globals the module reads (`g_chain_config`,
 * `g_dynamic_network_list`, `txContext`, `tmpContent`) directly rather
 * than dragging in the full app, and rely on the real implementations of
 * format_u64 / u64_from_BE so the format-fallback path is exercised
 * end-to-end.
 */

#include "unity.h"
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "shared_context.h"
#include "network.h"
#include "network_info.h"  // extern g_dynamic_network_list
#include "caller_app.h"
#include "wraps.h"  // extern g_tx_content

// =============================================================================
// Globals the module reads — provide storage here.
// =============================================================================

static chain_config_t s_chain_cfg = {.chain_id = 1, .ticker = "ETH", .coin_type = 60};

// =============================================================================
// Test fixtures / helpers
// =============================================================================

static void reset_globals(void) {
    memset(&txContext, 0, sizeof(txContext));
    memset(&tmpContent, 0, sizeof(tmpContent));
    memset(&g_tx_content, 0, sizeof(g_tx_content));
    txContext.content = &g_tx_content;
    g_dynamic_network_list = NULL;
    s_chain_cfg.chain_id = 1;
    strlcpy(s_chain_cfg.ticker, "ETH", sizeof(s_chain_cfg.ticker));
    g_chain_config = &s_chain_cfg;
}

// =============================================================================
// find_dynamic_network_by_chain_id
// =============================================================================

void test_find_dynamic_empty_list_returns_null(void) {
    TEST_ASSERT_NULL(find_dynamic_network_by_chain_id(1));
}

void test_find_dynamic_one_match(void) {
    network_info_t n = {0};
    n.chain_id = 4242;
    strlcpy(n.name, "TestNet", sizeof(n.name));
    strlcpy(n.ticker, "TST", sizeof(n.ticker));
    g_dynamic_network_list = &n;

    network_info_t *found = find_dynamic_network_by_chain_id(4242);
    TEST_ASSERT_EQUAL_PTR(found, &n);
    TEST_ASSERT_NULL(find_dynamic_network_by_chain_id(9999));
}

void test_find_dynamic_walks_list_and_finds_second(void) {
    network_info_t a = {0};
    a.chain_id = 11;
    network_info_t b = {0};
    b.chain_id = 22;
    a.node.next = (flist_node_t *) &b;
    g_dynamic_network_list = &a;

    TEST_ASSERT_EQUAL_PTR(find_dynamic_network_by_chain_id(11), &a);
    TEST_ASSERT_EQUAL_PTR(find_dynamic_network_by_chain_id(22), &b);
    TEST_ASSERT_NULL(find_dynamic_network_by_chain_id(33));
}

// =============================================================================
// get_network_name_from_chain_id
// =============================================================================

void test_get_name_known_hardcoded_returns_name(void) {
    uint64_t cid = 1;  // Ethereum
    const char *name = get_network_name_from_chain_id(&cid);
    TEST_ASSERT_NOT_NULL(name);
    TEST_ASSERT_EQUAL_STRING(name, "Ethereum");
}

void test_get_name_zero_chain_id_returns_null(void) {
    uint64_t cid = 0;
    TEST_ASSERT_NULL(get_network_name_from_chain_id(&cid));
}

void test_get_name_unknown_chain_id_returns_null(void) {
    uint64_t cid = 0xDEADBEEF;
    TEST_ASSERT_NULL(get_network_name_from_chain_id(&cid));
}

void test_get_name_dynamic_shadows_hardcoded(void) {
    // Inject a dynamic entry on chain_id=1 with a different name — it must
    // win over the hardcoded "Ethereum".
    network_info_t dyn = {0};
    dyn.chain_id = 1;
    strlcpy(dyn.name, "EthereumFork", sizeof(dyn.name));
    strlcpy(dyn.ticker, "FORK", sizeof(dyn.ticker));
    g_dynamic_network_list = &dyn;

    uint64_t cid = 1;
    const char *name = get_network_name_from_chain_id(&cid);
    TEST_ASSERT_EQUAL_STRING(name, "EthereumFork");
}

// =============================================================================
// get_network_as_string_from_chain_id
// =============================================================================

void test_get_as_string_known_copies_name(void) {
    char out[NETWORK_STRING_MAX_SIZE + 1];
    memset(out, 0, sizeof(out));
    TEST_ASSERT_TRUE(get_network_as_string_from_chain_id(out, sizeof(out), 137));  // Polygon
    TEST_ASSERT_EQUAL_STRING(out, "Polygon");
}

void test_get_as_string_unknown_formats_decimal(void) {
    char out[NETWORK_STRING_MAX_SIZE + 1];
    memset(out, 0, sizeof(out));
    TEST_ASSERT_TRUE(get_network_as_string_from_chain_id(out, sizeof(out), 4242));
    TEST_ASSERT_EQUAL_STRING(out, "4242");
}

void test_get_as_string_unknown_small_buffer_fails(void) {
    char out[2];  // not enough to hold "4242" + NUL
    TEST_ASSERT_FALSE(get_network_as_string_from_chain_id(out, sizeof(out), 4242));
}

// =============================================================================
// chain_is_ethereum_compatible
// =============================================================================

void test_chain_compatible_known_true(void) {
    uint64_t cid = 137;
    TEST_ASSERT_TRUE(chain_is_ethereum_compatible(&cid));
}

void test_chain_compatible_unknown_false(void) {
    uint64_t cid = 0xDEADBEEF;
    TEST_ASSERT_FALSE(chain_is_ethereum_compatible(&cid));
}

// =============================================================================
// app_compatible_with_chain_id
// =============================================================================

void test_app_compatible_same_chain_id(void) {
    s_chain_cfg.chain_id = 1;
    uint64_t cid = 1;
    TEST_ASSERT_TRUE(app_compatible_with_chain_id(&cid));
}

void test_app_compatible_both_in_table(void) {
    s_chain_cfg.chain_id = 1;  // Ethereum
    uint64_t cid = 137;        // Polygon
    TEST_ASSERT_TRUE(app_compatible_with_chain_id(&cid));
}

void test_app_compatible_target_unknown_rejected(void) {
    s_chain_cfg.chain_id = 1;  // Ethereum
    uint64_t cid = 0xDEADBEEF;
    TEST_ASSERT_FALSE(app_compatible_with_chain_id(&cid));
}

// =============================================================================
// get_tx_chain_id — dispatches on txContext.txType
// =============================================================================

void test_get_tx_chain_id_legacy_reads_v(void) {
    txContext.txType = LEGACY;
    // chainID encoded in v (BE)
    g_tx_content.v[0] = 0x00;
    g_tx_content.v[1] = 0x89;  // 137
    g_tx_content.vLength = 2;
    TEST_ASSERT_EQUAL(get_tx_chain_id(), 137);
}

void test_get_tx_chain_id_eip1559_reads_tmpcontent(void) {
    txContext.txType = EIP1559;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x00;
    tmpContent.txContent.chainID.value[1] = 0x01;  // 1
    tmpContent.txContent.chainID.length = 2;
    TEST_ASSERT_EQUAL(get_tx_chain_id(), 1);
}

void test_get_tx_chain_id_eip2930_reads_tmpcontent(void) {
    txContext.txType = EIP2930;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x10;
    tmpContent.txContent.chainID.value[1] = 0xA5;
    tmpContent.txContent.chainID.value[2] = 0xD4;
    tmpContent.txContent.chainID.value[3] = 0xE8;
    tmpContent.txContent.chainID.length = 4;
    TEST_ASSERT_EQUAL(get_tx_chain_id(), 0x10A5D4E8);
}

void test_get_tx_chain_id_eip7702_reads_tmpcontent(void) {
    txContext.txType = EIP7702;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x01;
    tmpContent.txContent.chainID.length = 1;
    TEST_ASSERT_EQUAL(get_tx_chain_id(), 1);
}

void test_get_tx_chain_id_unknown_type_returns_zero(void) {
    txContext.txType = 0x33;  // anything not listed
    TEST_ASSERT_EQUAL(get_tx_chain_id(), 0);
}

void test_get_network_as_string_uses_current_tx_chain_id(void) {
    // get_network_as_string() is a thin wrapper that reads the current
    // tx_chain_id and forwards to get_network_as_string_from_chain_id.
    txContext.txType = EIP1559;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x00;
    tmpContent.txContent.chainID.value[1] = 0x89;  // 137
    tmpContent.txContent.chainID.length = 2;
    char out[16] = {0};
    TEST_ASSERT_TRUE(get_network_as_string(out, sizeof(out)));
    TEST_ASSERT_EQUAL_STRING(out, "Polygon");
}

// =============================================================================
// get_displayable_ticker
// =============================================================================

void test_displayable_ticker_known_returns_table(void) {
    uint64_t cid = 137;  // Polygon
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg, true);
    TEST_ASSERT_EQUAL_STRING(t, "POL");
}

void test_displayable_ticker_falls_back_to_chain_cfg(void) {
    s_chain_cfg.chain_id = 999999;  // not in the table
    strlcpy(s_chain_cfg.ticker, "MYAPP", sizeof(s_chain_cfg.ticker));
    uint64_t cid = 999999;
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg, true);
    TEST_ASSERT_EQUAL_STRING(t, "MYAPP");
}

void test_displayable_ticker_unknown_returns_placeholder(void) {
    s_chain_cfg.chain_id = 1;  // chain_cfg won't match
    uint64_t cid = 0xDEADBEEF;
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg, true);
    TEST_ASSERT_EQUAL_STRING(t, "???");
}

void test_displayable_ticker_dynamic_shadows(void) {
    // Dynamic entry should win over hardcoded ticker when dynamic=true.
    network_info_t dyn = {0};
    dyn.chain_id = 1;
    strlcpy(dyn.ticker, "DYN", sizeof(dyn.ticker));
    g_dynamic_network_list = &dyn;

    uint64_t cid = 1;
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg, true);
    TEST_ASSERT_EQUAL_STRING(t, "DYN");

    // With dynamic=false, the dynamic list is bypassed → hardcoded wins.
    g_dynamic_network_list = &dyn;
    t = get_displayable_ticker(&cid, &s_chain_cfg, false);
    TEST_ASSERT_EQUAL_STRING(t, "ETH");
}

// =============================================================================
// get_clone_network_name
// =============================================================================

void test_clone_name_null_app_returns_null(void) {
    TEST_ASSERT_NULL(get_clone_network_name(NULL));
}

void test_clone_name_non_clone_returns_null(void) {
    caller_app_t app = {.name = "MyPlugin", .type = CALLER_TYPE_PLUGIN};
    TEST_ASSERT_NULL(get_clone_network_name(&app));
}

void test_clone_name_clone_returns_name(void) {
    caller_app_t app = {.name = "ETHClone", .type = CALLER_TYPE_CLONE};
    TEST_ASSERT_EQUAL_STRING(get_clone_network_name(&app), "ETHClone");
}

// =============================================================================
// Runner
// =============================================================================

void setUp(void) {
    reset_globals();
}
void tearDown(void) {
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_find_dynamic_empty_list_returns_null);
    RUN_TEST(test_find_dynamic_one_match);
    RUN_TEST(test_find_dynamic_walks_list_and_finds_second);
    RUN_TEST(test_get_name_known_hardcoded_returns_name);
    RUN_TEST(test_get_name_zero_chain_id_returns_null);
    RUN_TEST(test_get_name_unknown_chain_id_returns_null);
    RUN_TEST(test_get_name_dynamic_shadows_hardcoded);
    RUN_TEST(test_get_as_string_known_copies_name);
    RUN_TEST(test_get_as_string_unknown_formats_decimal);
    RUN_TEST(test_get_as_string_unknown_small_buffer_fails);
    RUN_TEST(test_chain_compatible_known_true);
    RUN_TEST(test_chain_compatible_unknown_false);
    RUN_TEST(test_app_compatible_same_chain_id);
    RUN_TEST(test_app_compatible_both_in_table);
    RUN_TEST(test_app_compatible_target_unknown_rejected);
    RUN_TEST(test_get_tx_chain_id_legacy_reads_v);
    RUN_TEST(test_get_tx_chain_id_eip1559_reads_tmpcontent);
    RUN_TEST(test_get_tx_chain_id_eip2930_reads_tmpcontent);
    RUN_TEST(test_get_tx_chain_id_eip7702_reads_tmpcontent);
    RUN_TEST(test_get_tx_chain_id_unknown_type_returns_zero);
    RUN_TEST(test_get_network_as_string_uses_current_tx_chain_id);
    RUN_TEST(test_displayable_ticker_known_returns_table);
    RUN_TEST(test_displayable_ticker_falls_back_to_chain_cfg);
    RUN_TEST(test_displayable_ticker_unknown_returns_placeholder);
    RUN_TEST(test_displayable_ticker_dynamic_shadows);
    RUN_TEST(test_clone_name_null_app_returns_null);
    RUN_TEST(test_clone_name_non_clone_returns_null);
    RUN_TEST(test_clone_name_clone_returns_name);
    return UNITY_END();
}
